<?php
/**
 * @file
 * Creates a filter that allows requiring or excluding entities selected
 * by another view.
 */

require_once 'other_view_handler_filter_entity.inc';

/**
 * Implements hook_views_api().
 */
function other_view_filter_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_data_alter().
 */
function other_view_filter_views_data_alter(&$data) {
  // @todo: Make this work with users, files, and other entity types.
  $data['node']['other_view']['title'] = 'Other view result';
  $data['node']['other_view']['help'] = 'Filters this view against results of selected other view.';
  $data['node']['other_view']['filter']['handler'] = 'other_view_handler_filter_entity';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function other_view_filter_form_views_ui_config_item_form_alter(&$form, &$form_state) {
  // Force single filter selection.
  if($form['#section'] == 'list_pane-filter-other_view') {
    $form['options']['value']['#multiple'] = 0;
  }
}